### ISSUE TITLE
Importing of GA4 data fails in the command line

### ISSUE THREAD

**Issue by lukerigbx** [matomo-org/plugin-GoogleAnalyticsImporter#277]
I'm trying to import Google Analytics 4 data into Matomo on-premise from the command line. The command seems to be failing right from the outset, however, and I get the error:
```
  [Google\ApiCore\ValidationException]                                                                              
  Could not map bindings for google.analytics.admin.v1alpha.AnalyticsAdminService/GetProperty to any Uri template.  
  Bindings: Array                                                                                                   
  (                                                                                                                 
      [name] => [property-id]                                                                                         
  )                                                                                                                 
  UriTemplates: Array                                                                                               
  (                                                                                                                 
      [0] => /v1alpha/{name=properties/*}                                                                           
  )            
```
where `[property-id]` is the property-id I have redacted. I am running the command such:
`php ./console googleanalyticsimporter:import-ga4-reports --property=331839734 --dates=2022-06-05,2022-09-22`.

I'm not sure why this is occuring, and have followed all of the guides on the Matomo website — this seems to be a bug?

**Comment by AltamashShaikh** [comment]
@lukerigbx Try - `php ./console googleanalyticsimporter:import-ga4-reports --property="properties/331839734" --dates=2022-06-05,2022-09-22`

**Comment by AltamashShaikh** [comment]
@lukerigbx Updated [doc](https://matomo.org/faq/general/running-the-google-analytics-import/) too.

**Comment by lukerigbx** [comment]
Thanks! That solves that problem, but the importer still throws an error:
```
ERROR [2022-09-21 14:52:41] 394755  Uncaught exception: Error: Call to undefined function Google\Protobuf\Internal\bccomp() in /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:959
Stack trace:
#0 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1300): Google\Protobuf\Internal\Message->convertJsonValueToProtoValue()
#1 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1239): Google\Protobuf\Internal\Message->mergeFromArrayJsonImpl()
#2 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1336): Google\Protobuf\Internal\Message->mergeFromJsonArray()
#3 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(793): Google\Protobuf\Internal\Message->parseFromJsonStream()
#4 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/gax/src/Transport/RestTransport.php(128): Google\Protobuf\Internal\Message->mergeFromJsonString()
#5 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(204): Google\ApiCore\Transport\RestTransport->Google\ApiCore\Transport\{closure}()
#6 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#7 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#8 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\Promise\TaskQueue->run()
#9 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(184): GuzzleHttp\Handler\CurlMultiHandler->tick()
#10 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute()
#11 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#12 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#13 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#14 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#15 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/analytics-data/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php(1083): GuzzleHttp\Promise\Promise->wait()
#16 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/Google/GoogleAnalyticsGA4QueryService.php(168): Google\Analytics\Data\V1beta\Gapic\BetaAnalyticsDataGapicClient->runReport()
#17 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/Google/GoogleAnalyticsGA4QueryService.php(111): Piwik\Plugins\GoogleAnalyticsImporter\Google\GoogleAnalyticsGA4QueryService->gaRunReport()
#18 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/Importers/VisitsSummary/RecordImporterGA4.php(62): Piwik\Plugins\GoogleAnalyticsImporter\Google\GoogleAnalyticsGA4QueryService->query()
#19 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/ImporterGA4.php(471): Piwik\Plugins\GoogleAnalyticsImporter\Importers\VisitsSummary\RecordImporterGA4->importRecords()
#20 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/ImporterGA4.php(406): Piwik\Plugins\GoogleAnalyticsImporter\ImporterGA4->importDay()
#21 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php(247): Piwik\Plugins\GoogleAnalyticsImporter\ImporterGA4->import()
#22 /var/www/html/matomo/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php(54): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->executeImpl()
#23 /var/www/html/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->execute()
#24 /var/www/html/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
#25 /var/www/html/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
#26 [internal function]: Symfony\Component\Console\Application->doRun()
#27 /var/www/html/matomo/core/Console.php(135): call_user_func()
#28 /var/www/html/matomo/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#29 /var/www/html/matomo/core/Console.php(136): Piwik\Access::doAsSuperUser()
#30 /var/www/html/matomo/core/Console.php(87): Piwik\Console->doRunImpl()
#31 /var/www/html/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#32 /var/www/html/matomo/console(32): Symfony\Component\Console\Application->run()
#33 {main}
Uncaught exception in /var/www/html/matomo/plugins/GoogleAnalyticsImporter/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php line 959:
Call to undefined function Google\Protobuf\Internal\bccomp()
```

**Comment by AltamashShaikh** [comment]
@lukerigbx is php-bcmath installed?

**Comment by lukerigbx** [comment]
@AltamashShaikh, ah! that seemed to be the answer. It works now, thank you!
