### ISSUE TITLE
Unable to import Mobile App from GA4

### ISSUE THREAD

**Issue by Starker3** [matomo-org/plugin-GoogleAnalyticsImporter#338]
When importing a mobile app with the latest version of the plugin, we get the following error:

```
ERROR [2023-01-31 02:12:14] 14897 rema.matomo.cloud  Uncaught exception: Exception: URLs: You must specify at least one URL for the website. in /var/www/html/plugins/CorePluginsAdmin/SettingsMetadata.php:48
Stack trace:
#0 /var/www/html/plugins/SitesManager/API.php(793): Piwik\Plugins\CorePluginsAdmin\SettingsMetadata->setPluginSettings(Array, Array)
#1 /var/www/html/plugins/SitesManager/API.php(706): Piwik\Plugins\SitesManager\API->setAndValidateMeasurableSettings(0, 'website', Array)
#2 [internal function]: Piwik\Plugins\SitesManager\API->addSite('test', '', '1', '0', '', '', NULL, '', 'Europe/Oslo', 'NOK', NULL, '2016-11-15', NULL, NULL, 'mobileapp', Array, NULL, NULL)
#3 /var/www/html/core/API/Proxy.php(244): call_user_func_array(Array, Array)
#4 /var/www/html/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
#5 /var/www/html/core/API/Proxy.php(335): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
#6 /var/www/html/core/API/Request.php(267): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'addSite', Array)
#7 /var/www/html/core/API/Request.php(560): Piwik\API\Request->process()
#8 /var/www/html/plugins/GoogleAnalyticsImporter/ImporterGA4.php(199): Piwik\API\Request::processRequest('SitesManager.ad...', Array)
#9 /var/www/html/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php(126): Piwik\Plugins\GoogleAnalyticsImporter\ImporterGA4->makeSite('properties/...', 'Europe/Oslo', 'mobileapp', Array)
#10 /var/www/html/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php(57): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->executeImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/core/Console.php(135): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#17 /var/www/html/core/Console.php(136): Piwik\Access::doAsSuperUser(Object(Closure))
#18 /var/www/html/core/Console.php(87): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/console(32): Symfony\Component\Console\Application->run()
#21 {main}
```

However, it isn't possible to set a URL through the UI when starting an import.
![image](https://user-images.githubusercontent.com/20905821/215642795-04813af2-511e-4a6f-9033-e40c26516c43.png)

**Comment by AltamashShaikh** [comment]
@Starker3 Actually in GA4 we don't get the website URL from the API and we use the propertyName instead of the URL and that is causing the issue, may be in case of mobile app we need to set the URL as dummy URL to make it work, will check if setting that won't create a problem
![Screenshot from 2023-01-31 08-57-43](https://user-images.githubusercontent.com/14902277/215655703-27d1f4bc-877c-4f00-9c15-66a8c416452d.png)

**Comment by AltamashShaikh** [comment]
Ignore my previous comment, we were sending null only for mobile, Its a regression, will prepare a fix for it
